import type { HotspotBlock } from "@/lib/hotspots"

export type ProductData = {
  name: string
  categoryLabel: string
  tagline: string
  story: [string, string]
  details: { label: string; value: string }[]
  sizes: string[]
  unit: string
  heroImg: string
  storyImg: string
  // Rich fields for Windows & Doors "system" product pages (shared with Classic)
  description?: string
  certification?: string
  configurations?: string[]
  profiles?: { label: string; value: string }[]
  performance?: string[]
  glassOptions?: string[]
  finishOptions?: string[]
  gallery?: string[]
  projectExample?: { title: string; location: string; desc: string; img: string }
  // Optional - interactive hotspot image (Admin > Products)
  hotspots?: HotspotBlock
  // Optional - page blocks (Admin > Products), JSON
  blocks?: string
}

/** Signature Luxe collection overview copy. */
export const COLLECTION_INTRO = [
  "The Signature Luxe Collection is intended for premium residential projects requiring both architectural refinement and improved technical performance.",
  "It includes thermally broken aluminium systems for improved energy efficiency and ultra-slim panoramic systems for larger openings, minimal sightlines and uninterrupted views.",
  "All systems are custom manufactured for the project and specified against applicable BASIX, NatHERS and Australian Standards requirements.",
]

const COMPLIANCE = "All systems are custom manufactured for the project and specified against applicable BASIX, NatHERS and Australian Standards requirements."

const ALL_PRODUCTS: Record<string, Record<string, ProductData>> = {
  "windows-doors": {
    "asg-102-thermal-sliding": {"name":"Series 102 Thermal Break Sliding","categoryLabel":"Windows & Doors","tagline":"Expansive openings with improved thermal performance.","story":["The Atelier Signature Series 102 Thermal Break Sliding System is designed for expansive glazing with improved thermal performance - an insulating polyamide barrier separates the internal and external aluminium sections to reduce heat transfer and condensation.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/signature/asg-102-thermal-sliding/home.png","storyImg":"/products/signature/asg-102-thermal-sliding/product.png","description":"The Atelier Signature Series 102 Thermal Break Sliding System is designed for expansive glazing with improved thermal performance - an insulating polyamide barrier separates the internal and external aluminium sections to reduce heat transfer and condensation.","certification":"AS 2047 & AS 1288 Certified","configurations":["Horizontal sliding panels on a precision track","Large glazed openings","Double-glazed thermal configurations"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Thermal barrier","value":"Insulating polyamide thermal break"},{"label":"Profile thickness","value":"2.0mm"},{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Hardware","value":"Doric sliding & locking"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Thermal break reduces heat transfer","Improved comfort and reduced condensation","Smooth operation at scale"],"glassOptions":["Double glazed (IGU)","Low-E performance glazing","Laminated acoustic & safety glass"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/signature/asg-102-thermal-sliding/product.png","/products/signature/asg-102-thermal-sliding/side-profile.png","/products/signature/asg-102-thermal-sliding/home.png"],"projectExample":{"title":"Architectural Residence","location":"Sydney, NSW","desc":"Thermally broken sliding doors deliver premium comfort and energy performance.","img":"/products/signature/asg-102-thermal-sliding/home.png"}},
    "asg-102-thermal-casement": {"name":"Series 102 Thermal Break Casement","categoryLabel":"Windows & Doors","tagline":"A refined door with improved thermal performance.","story":["The Atelier Signature Series 102 Thermal Break Casement Door creates a light-filled connection between spaces while improving insulation through its thermally separated aluminium frame.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/signature/asg-102-thermal-casement/home.png","storyImg":"/products/signature/asg-102-thermal-casement/product.png","description":"The Atelier Signature Series 102 Thermal Break Casement Door creates a light-filled connection between spaces while improving insulation through its thermally separated aluminium frame.","certification":"AS 2047 & AS 1288 Certified","configurations":["Side-hinged door, inward or outward","Full-height glazing","Thermally broken framing"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Thermal barrier","value":"Insulating polyamide thermal break"},{"label":"Profile thickness","value":"2.0mm"},{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Hardware","value":"Kinlong lever, hinges & locking"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Thermally broken frame for comfort","Clean sightlines and strong construction","Reduced condensation with double glazing"],"glassOptions":["Double glazed (IGU)","Low-E performance glazing","Laminated acoustic & safety glass"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/signature/asg-102-thermal-casement/product.png","/products/signature/asg-102-thermal-casement/side-profile.png","/products/signature/asg-102-thermal-casement/home.png"],"projectExample":{"title":"Hillside Home","location":"Northern Beaches, NSW","desc":"Thermal break casement doors open living spaces to the view with improved comfort.","img":"/products/signature/asg-102-thermal-casement/home.png"}},
    "asg-102-thermal-awning": {"name":"Series 102 Thermal Break Awning","categoryLabel":"Windows & Doors","tagline":"Light, air and everyday comfort.","story":["The Atelier Signature Series 102 Thermal Break Awning Window opens outward from the bottom to introduce fresh air while maintaining a streamlined, thermally broken frame.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/signature/asg-102-thermal-awning/home.png","storyImg":"/products/signature/asg-102-thermal-awning/product.png","description":"The Atelier Signature Series 102 Thermal Break Awning Window opens outward from the bottom to introduce fresh air while maintaining a streamlined, thermally broken frame.","certification":"AS 2047 & AS 1288 Certified","configurations":["Top-hinged sash opening outward from the bottom","Thermally broken framing","Double-glazing options"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Thermal barrier","value":"Insulating polyamide thermal break"},{"label":"Profile thickness","value":"1.8mm"},{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Hardware","value":"Doric operating & locking"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Thermally broken for comfort","Controlled outward ventilation","Streamlined appearance"],"glassOptions":["Double glazed (IGU)","Low-E performance glazing","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/signature/asg-102-thermal-awning/product.png","/products/signature/asg-102-thermal-awning/side-profile.png","/products/signature/asg-102-thermal-awning/home.png"],"projectExample":{"title":"Contemporary Home","location":"Sydney, NSW","desc":"Thermal break awning windows deliver light, air and comfort throughout the home.","img":"/products/signature/asg-102-thermal-awning/home.png"}},
    "asg-120-sunroom": {"name":"Series 120 Sunroom & Skylight","categoryLabel":"Windows & Doors","tagline":"Architecture shaped by natural light.","story":["The Series 120 transforms patios, courtyards and underused external areas into protected, light-filled spaces - its roof and wall glazing introducing natural light from multiple directions with fixed and operable panels.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"120mm"},{"label":"Glazing","value":"5mm toughened + 1.14 PVB + 5mm laminated toughened"},{"label":"Certification","value":"-"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/Signature Luxe.png","storyImg":"/Atelier_Classic.png","description":"The Series 120 transforms patios, courtyards and underused external areas into protected, light-filled spaces - its roof and wall glazing introducing natural light from multiple directions with fixed and operable panels.","configurations":["Skylights, glazed roofs and sunrooms","Fixed glazing with optional operable roof vents","Fixed glazing with optional sliding, awning or casement wall panels"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"3.0mm"},{"label":"Structure width","value":"120mm"},{"label":"Glazing","value":"5mm toughened + 1.14 PVB + 5mm laminated toughened"},{"label":"Roof","value":"Fixed glazing with optional roof vents"},{"label":"Frame finishes","value":"Powder-coated to suit the project"}],"performance":["Natural light from multiple directions","Custom architectural shapes and configurations","Balances daylight, ventilation and weather protection"],"glassOptions":["Laminated toughened safety glass (5 / 1.14 PVB / 5)","Other glazing to project requirements"],"finishOptions":["Powder-coated finishes to suit the project"],"gallery":["/Signature Luxe.png","/Classic.png","/Atelier_Signature.png","/Atelier_Classic.png"],"projectExample":{"title":"Winter Garden","location":"Sydney, NSW","desc":"A Series 120 sunroom encloses a courtyard into a light-filled, year-round space.","img":"/Signature Luxe.png"}},
    "asg-39-pro": {"name":"ASG39PRO Panoramic","categoryLabel":"Windows & Doors","tagline":"Ultra-slim panoramic sliding - minimal frame, maximum view.","story":["The Ultra-Slim Panoramic Sliding System reduces the vertical interlock to just 20mm, creating a refined transition between glass panels. Large-format insulated glazing and premium pulley hardware deliver smooth, controlled movement and uninterrupted views.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"39mm sightline"},{"label":"Glazing","value":"8mm + 22A + 8mm insulated ultra-clear"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/signature/asg-39-pro/home.png","storyImg":"/products/signature/asg-39-pro/product.png","description":"The Ultra-Slim Panoramic Sliding System reduces the vertical interlock to just 20mm, creating a refined transition between glass panels. Large-format insulated glazing and premium pulley hardware deliver smooth, controlled movement and uninterrupted views.","certification":"Air & Water Class 5 · Wind Class 10","configurations":["Large-format horizontal sliding panels","Sliding panels up to 12 m²","Fixed panels up to 18 m²"],"profiles":[{"label":"Vertical interlock","value":"20mm visible"},{"label":"Outer frame","value":"50mm visible"},{"label":"Top rail","value":"60mm visible"},{"label":"Profile thickness","value":"2.0-5.0mm"},{"label":"Structure width","value":"39mm sightline"},{"label":"Glazing","value":"8mm + 22A + 8mm insulated ultra-clear"},{"label":"Pulleys","value":"POM or 304 stainless-steel pulley set"},{"label":"Thermal","value":"Polycarbonate thermal-insulation component"},{"label":"Frame colours","value":"Skin Black · Hepburn Black Grey · Starry Grey · Simba Coffee"}],"performance":["Ultra-slim 20mm interlock for uninterrupted views","Up to 35 dB acoustic; 1.2-1.8 W/(m²K) thermal","Air & Water Class 5, Wind Class 10"],"glassOptions":["8+22A+8 insulated ultra-clear","Low-E / acoustic / structural options to suit project"],"finishOptions":["Skin Black","Hepburn Black Grey","Starry Grey","Simba Coffee","Custom to order"],"gallery":["/products/signature/asg-39-pro/product.png","/products/signature/asg-39-pro/side-profile.png","/products/signature/asg-39-pro/home.png"],"projectExample":{"title":"Panoramic Villa","location":"Northern Beaches, NSW","desc":"ASG39PRO panoramic sliders open an entire living wall to the view with barely-there framing.","img":"/products/signature/asg-39-pro/home.png"}},
  },
}

export function getProduct(category: string, product: string): ProductData | null {
  return ALL_PRODUCTS[category]?.[product] ?? null
}

export function listProducts(category: string): { slug: string; data: ProductData }[] {
  const c = ALL_PRODUCTS[category]
  if (!c) return []
  return Object.entries(c).map(([slug, data]) => ({ slug, data }))
}

/** Key prefix used for Signature products in Admin > Products overrides. */
export const signatureOverrideCategory = (category: string) => `signature-${category}`
