import type { HotspotBlock } from "@/lib/hotspots"

// AUTO-GENERATED base - Classic product data (Signature-style structure).
export type ProductData = {
  name: string
  categoryLabel: string
  tagline: string
  story: [string, string]
  details: { label: string; value: string }[]
  sizes: string[]
  unit: string
  heroImg: string
  storyImg: string
  // Optional - richer fields used by Windows & Doors "system" product pages
  description?: string
  certification?: string
  configurations?: string[]
  profiles?: { label: string; value: string }[]
  performance?: string[]
  glassOptions?: string[]
  finishOptions?: string[]
  gallery?: string[]
  projectExample?: { title: string; location: string; desc: string; img: string }
  // Optional - Bathroom "package style" product pages (fixed inclusions + configurable options)
  packageStyle?: string
  fixedInclusions?: { label: string; value: string }[]
  // Optional - short feature line shown under the tagline on joinery range cards
  features?: string
  // Optional - interactive hotspot image (Admin > Products)
  hotspots?: HotspotBlock
  // Optional - page blocks (Admin > Products), JSON
  blocks?: string
  /** Shown on the card as "Coming soon"; the card does not open a page. */
  comingSoon?: boolean
}

export type CategoryMeta = {
  label: string
  headline: string
  body: string[]
  /** Optional Story-section copy; falls back to `body` when absent (keeps hero intro independent) */
  story?: string[]
  heroImg: string
  storyImg: string
}

export const CATEGORY_META: Record<string, CategoryMeta> = {
  "windows-doors": { label: "Windows & Doors", headline: "The Classic Collection.", body: ["The Atelier Classic Collection brings together architectural aluminium window and door systems, precise specification and project-specific manufacturing for new homes, renovations and residential developments.", "Designed around your architectural plans, every package is tailored to the project - from opening configurations and glazing through to frame finishes, hardware and performance requirements. The result is a complete window and door package that looks refined, performs as required and arrives ready for the next stage of your build."], story: ["Classic is our curated range for projects that demand clean design, dependable performance and flexibility without unnecessary complexity.", "From fixed and awning windows to expansive sliding and stacking door systems, each element is selected and configured around the architecture of the home. Opening sizes, panel configurations, glazing, wind classification, energy performance, hardware and powdercoat finishes are resolved as one coordinated package.", "Rather than selecting an off-the-shelf window and adapting the project around it, we specify the system around the project. Every system is specified to comply with AS 2047, AS 1288 and the project's BASIX or NatHERS requirements."], heroImg: "/window-hero.png", storyImg: "/Atelier_Classic.png" },
  "joinery": { label: "Custom Joinery", headline: "Made for the home you're building.", body: ["Joinery that combines refined proportions, premium materials and precise detailing - designed to your project and made to fit as built."], story: ["Premium materials, precise detailing and finishes selected to work together. Statement kitchens, butler's pantries, wardrobes, laundries, bathroom cabinetry and automated joinery - each piece made specifically for your project and installed by the Atelier team.", "Every package is developed around your architectural plans, the material palette and how the space will actually be used, then documented in shop drawings before manufacture - with standard construction tolerances built into the detailing. Renovating? We design around your existing room, working from a measured drawing or your builder's dimensions, verified before anything is made.", "Custom joinery, done the way construction actually happens."], heroImg: "/joinery-hero.png", storyImg: "/joinery-story.png" },
  "bathrooms": { label: "Bathroom Packages", headline: "Five fully coordinated bathrooms.", body: ["Complete, coordinated bathroom packages in five distinct styles - every fixture, finish and surface selected to work together as one considered whole.", "Choose your style, then tailor the vanity, toilet, tiling and supply or install to suit your project. Final individual-product and complete-room photography will follow."], heroImg: "/bathroom-hero.png", storyImg: "/Atelier_Classic.png" },
}

export const ALL_PRODUCTS: Record<string, Record<string, ProductData>> = {
  "windows-doors": {
    "asg-series-102": { name: "ASG Series 102", categoryLabel: "Windows & Doors", tagline: "Sliding Doors & Windows - our most specified system.", story: ["Our most specified system. Slim 102mm sliding panels glide on a precision track to open living spaces to the outdoors without intruding on the room.", "Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."], details: [{ label: "Extrusion", value: "6063-T5 aluminium" }, { label: "Structure width", value: "102mm" }, { label: "Certification", value: "AS 2047 & AS 1288" }, { label: "Manufacture", value: "Custom to approved plans" }], sizes: ["Custom to project plans"], unit: "package", heroImg: "/products/classic/windows/ASG 102 Series Sliding Window Doors/ASG102-Luxury Home.png", storyImg: "/products/classic/windows/ASG 102 Series Sliding Window Doors/ASG102-Luxury Home 2.png", description: "Our most specified system. Slim 102mm sliding panels glide on a precision track to open living spaces to the outdoors without intruding on the room.", certification: "AS 2047 & AS 1288 Certified", profiles: [{ label: "Extrusion", value: "6063-T5 aluminium" }, { label: "Profile thickness", value: "2.0mm" }, { label: "Structure width", value: "102mm" }, { label: "Glazing", value: "Double-tempered 5+12A+5mm / 6+12A+6mm / other glazing options" }, { label: "Hardware", value: "Doric" }, { label: "Insect screen", value: "Aluminium / fibreglass / stainless steel / retractable" }, { label: "Frame colours", value: "Matt Black · Monument · Pure White · custom to order" }], performance: ["Slim sightlines for expansive glazed openings", "Smooth-gliding precision track", "Double-tempered glazing for safety and comfort"], configurations: ["2, 3 & 4 panel sliding doors", "Multi-panel stacking doors", "Sliding windows", "Fixed & highlight windows", "Corner (90°) sliding configurations"], glassOptions: ["Double-tempered (5+12A+5 / 6+12A+6)", "Low-E performance glazing", "Laminated acoustic & safety glass", "Tinted (grey, bronze, neutral)"], finishOptions: ["Matt Black", "Monument", "Pure White", "Anodised silver / bronze", "Custom powder-coat to order"], gallery: ["/products/classic/windows/ASG 102 Series Sliding Window Doors/AS102-Window.png","/products/classic/windows/ASG 102 Series Sliding Window Doors/ASG102-Luxury Home 1.png","/products/classic/windows/ASG 102 Series Sliding Window Doors/ASG102-Side Profile.png","/products/classic/windows/ASG 102 Series Sliding Window Doors/ASG102-Luxury Home.png"], projectExample: { title: "Hillside Residence", location: "Northern Beaches, NSW", desc: "Series 102 sliding doors open expansive living spaces to the outdoors while meeting stringent performance targets.", img: "/products/classic/windows/ASG 102 Series Sliding Window Doors/ASG102-Luxury Home.png" } },
    "asg-102-awning": {"name":"ASG 102 Awning Window","categoryLabel":"Windows & Doors","tagline":"Natural light without compromising ventilation.","story":["The Atelier Classic Series 102 Awning Window combines expansive fixed glazing with practical operable panels - bringing natural light and broad views into the home while providing controlled airflow when required.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG 102 Series Awning Windows/ASG102-Awning winbdow-Luxury Home.png","storyImg":"/products/classic/windows/ASG 102 Series Awning Windows/ASG102-Awning winbdow-Luxury Home 2.png","description":"The Atelier Classic Series 102 Awning Window combines expansive fixed glazing with practical operable panels - bringing natural light and broad views into the home while providing controlled airflow when required.","certification":"AS 2047 & AS 1288 Certified","configurations":["Two side awning sashes with central fixed glazing","Fixed lower panels","Outward-opening awning operation"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"2.0mm"},{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Hardware","value":"Doric awning hardware"},{"label":"Insect screen","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Controlled ventilation through side awning panels","Expansive fixed glazing for natural light","Double-glazing options available"],"glassOptions":["5+12A+5 toughened","6+12A+6 toughened","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG 102 Series Awning Windows/ASG102-Awning Window.png","/products/classic/windows/ASG 102 Series Awning Windows/ASG102-Awning winbdow-Luxury Home 2.png","/products/classic/windows/ASG 102 Series Awning Windows/ASG102-Side Profile.png"],"projectExample":{"title":"Family Residence","location":"Sydney, NSW","desc":"Series 102 awning windows bring light and airflow to living and bedroom spaces.","img":"/products/classic/windows/ASG 102 Series Awning Windows/ASG102-Awning winbdow-Luxury Home.png"}},
    "asg-102-casement": {"name":"ASG 102 Casement Door","categoryLabel":"Windows & Doors","tagline":"A clean transition between indoors and out.","story":["The Atelier Classic Series 102 Casement Door introduces natural light and open views through a refined full-height glazed design, with slim aluminium framing and minimal hardware for a modern architectural appearance.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG 102 Series Casement Doors/ASG102 Casement Doors-Luxury Home.png","storyImg":"/products/classic/windows/ASG 102 Series Casement Doors/ASG102 Casement Doors-Luxury Home.png","description":"The Atelier Classic Series 102 Casement Door introduces natural light and open views through a refined full-height glazed design, with slim aluminium framing and minimal hardware for a modern architectural appearance.","certification":"AS 2047 & AS 1288 Certified","configurations":["Side-hinged casement operation","Full-height glazed door","Customisable size, glazing and hardware"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"2.0mm"},{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Hardware","value":"Kinlong lever handle & locking"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Slim framing with clean sightlines","Robust profile with double-glazing options","Ideal for balconies, courtyards and pool areas"],"glassOptions":["5+12A+5 toughened","6+12A+6 toughened","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG 102 Series Casement Doors/ASG102 Casement Door.png","/products/classic/windows/ASG 102 Series Casement Doors/ASG102 Casement Doors-Side Profile.png"],"projectExample":{"title":"Courtyard House","location":"Sydney, NSW","desc":"Series 102 casement doors open living spaces to a landscaped courtyard.","img":"/products/classic/windows/ASG 102 Series Casement Doors/ASG102 Casement Doors-Luxury Home.png"}},
    "asg-102-pocket": {"name":"ASG 102 Pocket Sliding","categoryLabel":"Windows & Doors","tagline":"Designed to disappear.","story":["The Atelier Classic Series 102 Pocket Sliding System allows the glazed panel to slide completely into the adjoining wall cavity, leaving the opening clear and uninterrupted.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG 102 Series Pocket Sliding Door/ASG102 Pocket Home.png","storyImg":"/products/classic/windows/ASG 102 Series Pocket Sliding Door/ASG102 Pocket Home.png","description":"The Atelier Classic Series 102 Pocket Sliding System allows the glazed panel to slide completely into the adjoining wall cavity, leaving the opening clear and uninterrupted.","certification":"AS 2047 & AS 1288 Certified","configurations":["Sliding panel retracts into a concealed wall cavity","Large glazed panels","Clear, uninterrupted opening"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"2.0mm"},{"label":"Structure width","value":"102mm"},{"label":"Glazing","value":"5+12A+5 / 6+12A+6 toughened"},{"label":"Hardware","value":"Top China Brand or Australian Doric"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Panel disappears into the wall cavity","Maximises usable floor area","Strong indoor-outdoor connection"],"glassOptions":["5+12A+5 toughened","6+12A+6 toughened","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG 102 Series Pocket Sliding Door/ASG102 Pocket Sliding Door.png","/products/classic/windows/ASG 102 Series Pocket Sliding Door/ASG102 Pocket Sliding Door-Side Profile.png"],"projectExample":{"title":"Alfresco Living","location":"Northern Beaches, NSW","desc":"Series 102 pocket sliders vanish into the wall to connect living and alfresco areas.","img":"/products/classic/windows/ASG 102 Series Pocket Sliding Door/ASG102 Pocket Home.png"}},
    "asg-102-louvre": {"name":"ASG 102 Glass Louvre","categoryLabel":"Windows & Doors","tagline":"Ventilation designed around the space.","story":["The Atelier Classic Series 102 Glass Louvre Window lets airflow be adjusted to changing weather and ventilation needs, its horizontal glass blades opening partially or fully while keeping a clean architectural appearance.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"102mm"},{"label":"Type","value":"Ventilation designed around the space."},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG 102 Series Louvre Glass/ASG102 Louvre Glass Luxury home.png","storyImg":"/products/classic/windows/ASG 102 Series Louvre Glass/ASG102 Louvre Glass Luxury home.png","description":"The Atelier Classic Series 102 Glass Louvre Window lets airflow be adjusted to changing weather and ventilation needs, its horizontal glass blades opening partially or fully while keeping a clean architectural appearance.","certification":"AS 2047 & AS 1288 Certified","configurations":["Manual handle louvre mechanism","Horizontal adjustable glass blades","Partial or full opening"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"2.0mm"},{"label":"Structure width","value":"102mm"},{"label":"Blade glass","value":"5mm toughened"},{"label":"Hardware","value":"Kinlong manual louvre operator"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Adjustable natural ventilation","Clean architectural appearance","Suited to bathrooms, kitchens and living areas"],"glassOptions":["5mm toughened blade glass","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG 102 Series Louvre Glass/ASG102 Louvre Glass.png","/products/classic/windows/ASG 102 Series Louvre Glass/ASG102 Louvre Glass Luxury home.png"],"projectExample":{"title":"Coastal Bathroom","location":"Sydney, NSW","desc":"Series 102 louvres provide adjustable ventilation to a light-filled bathroom.","img":"/products/classic/windows/ASG 102 Series Louvre Glass/ASG102 Louvre Glass Luxury home.png"}},
    "asg-series-86": {"name":"ASG Series 86","categoryLabel":"Windows & Doors","tagline":"Space-efficient sliding for everyday living.","story":["The Atelier Classic Series 86 Sliding System offers a clean, space-efficient way to connect living areas with balconies, patios and gardens - its panels sliding without projecting into the room.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"86mm"},{"label":"Glazing","value":"5+9A+5 toughened (double-glaze ready)"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG 86 Sliding Doors Windows/ASG86 Sliding Doors.png","storyImg":"/products/classic/windows/ASG 86 Sliding Doors Windows/ASG86 Sliding Doors.png","description":"The Atelier Classic Series 86 Sliding System offers a clean, space-efficient way to connect living areas with balconies, patios and gardens - its panels sliding without projecting into the room.","certification":"AS 2047 & AS 1288 Certified","configurations":["Horizontal sliding panels on an aluminium track","2 & 3 panel configurations","Sliding windows and doors"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"1.6mm"},{"label":"Structure width","value":"86mm"},{"label":"Glazing","value":"5+9A+5 toughened (double-glaze ready)"},{"label":"Hardware","value":"Siegenia or Doric"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Space-efficient, non-projecting operation","Double-glazing options","Dependable everyday performance"],"glassOptions":["5+9A+5 toughened","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG 86 Sliding Doors Windows/ASG86 Sliding Door.png","/products/classic/windows/ASG 86 Sliding Doors Windows/Side Profile.png"],"projectExample":{"title":"Suburban New Build","location":"Western Sydney, NSW","desc":"Series 86 sliding doors and windows deliver comfortable, compliant performance across a family home.","img":"/products/classic/windows/ASG 86 Sliding Doors Windows/ASG86 Sliding Doors.png"}},
    "asg-86-awning": {"name":"ASG 86 Awning Window","categoryLabel":"Windows & Doors","tagline":"Practical ventilation, clean contemporary design.","story":["The Series 86 Awning Window introduces fresh air and natural light through a top-hinged sash that opens outward from the bottom, delivering controlled ventilation with a clean architectural finish.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"86mm"},{"label":"Glazing","value":"5+9A+5 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG86 Awning Windows/ASG86 Home.png","storyImg":"/products/classic/windows/ASG86 Awning Windows/ASG86 Home.png","description":"The Series 86 Awning Window introduces fresh air and natural light through a top-hinged sash that opens outward from the bottom, delivering controlled ventilation with a clean architectural finish.","certification":"AS 2047 & AS 1288 Certified","configurations":["Top-hinged sash opening outward from the bottom","Controlled ventilation","Double-glazing options"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"1.6mm"},{"label":"Structure width","value":"86mm"},{"label":"Glazing","value":"5+9A+5 toughened"},{"label":"Hardware","value":"Doric operating & locking"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Controlled outward ventilation","Durable aluminium framing","Suited to bedrooms, kitchens and living areas"],"glassOptions":["5+9A+5 toughened","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG86 Awning Windows/ASG86 Awning Window.png","/products/classic/windows/ASG86 Awning Windows/Side Profile.png"],"projectExample":{"title":"Coastal Home","location":"Central Coast, NSW","desc":"Series 86 awning windows deliver airflow and light across bedrooms and living areas.","img":"/products/classic/windows/ASG86 Awning Windows/ASG86 Home.png"}},
    "asg-series-75": {"name":"ASG Series 75","categoryLabel":"Windows & Doors","tagline":"Folding doors that fold back the boundary.","story":["The Series 75 Folding Door System lets multiple glazed panels fold and stack compactly to the side of the opening, creating a broad connection between internal living spaces and the outdoors.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"75mm"},{"label":"Glazing","value":"5+12A+5 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG75 Folding Doors/ASG75 Folding Doors.png","storyImg":"/products/classic/windows/ASG75 Folding Doors/ASG75 Folding Doors.png","description":"The Series 75 Folding Door System lets multiple glazed panels fold and stack compactly to the side of the opening, creating a broad connection between internal living spaces and the outdoors.","certification":"AS 2047 & AS 1288 Certified","configurations":["Multiple hinged panels fold and stack to the side","Inward or outward folding","Multi-panel arrangements to suit the opening"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"1.8mm"},{"label":"Structure width","value":"75mm"},{"label":"Glazing","value":"5+12A+5 toughened"},{"label":"Hardware","value":"LSMA folding hardware"},{"label":"Flyscreens","value":"0.5mm folding aluminium flyscreen"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Panels fold and stack compactly","Broad, unobstructed opening","Connects living, dining and alfresco areas"],"glassOptions":["5+12A+5 toughened","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG75 Folding Doors/ASG75 Folding Door.png","/products/classic/windows/ASG75 Folding Doors/ASG75 Folding Doors Side Profile.png"],"projectExample":{"title":"Alfresco Entertainer","location":"Sydney, NSW","desc":"Series 75 folding doors open an entire wall to a covered alfresco area.","img":"/products/classic/windows/ASG75 Folding Doors/ASG75 Folding Doors.png"}},
    "asg-series-101": {"name":"ASG Series 101","categoryLabel":"Windows & Doors","tagline":"Hung windows - vertical ventilation, timeless design.","story":["The Series 101 Hung Window provides natural ventilation through a vertical sliding sash that stays within the plane of the window, so it doesn't interfere with furnishings, walkways or landscaping.","Custom manufactured to your approved plans and specified to comply with the applicable BASIX, NatHERS and Australian Standards requirements."],"details":[{"label":"Structure width","value":"101mm"},{"label":"Glazing","value":"5+12A+5 toughened"},{"label":"Certification","value":"AS 2047 & AS 1288"},{"label":"Manufacture","value":"Custom to approved plans"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/products/classic/windows/ASG101 Hung Windows/Hung Windows.png","storyImg":"/products/classic/windows/ASG101 Hung Windows/Hung Windows 2.png","description":"The Series 101 Hung Window provides natural ventilation through a vertical sliding sash that stays within the plane of the window, so it doesn't interfere with furnishings, walkways or landscaping.","certification":"AS 2047 & AS 1288 Certified","configurations":["Vertical sliding sash operation","Single-hung or double-hung","Within-plane operation"],"profiles":[{"label":"Extrusion","value":"6063-T5 aluminium"},{"label":"Profile thickness","value":"1.5mm"},{"label":"Structure width","value":"101mm"},{"label":"Glazing","value":"5+12A+5 toughened"},{"label":"Hardware","value":"Doric sash hardware"},{"label":"Flyscreens","value":"Aluminium / fibreglass / stainless steel / retractable"},{"label":"Frame colours","value":"Matt Black · Monument · Pure White · custom to order"}],"performance":["Vertical sliding ventilation","Stays within the window plane","Suited to bedrooms, kitchens and upper storeys"],"glassOptions":["5+12A+5 toughened","Other glazing to project requirements"],"finishOptions":["Matt Black","Monument","Pure White","Custom powder-coat to order"],"gallery":["/products/classic/windows/ASG101 Hung Windows/ASG101 Hung Windows.png","/products/classic/windows/ASG101 Hung Windows/Hung Windows 2.png","/products/classic/windows/ASG101 Hung Windows/Side Profile.png"],"projectExample":{"title":"Heritage-Style Home","location":"Sydney, NSW","desc":"Series 101 hung windows suit a refined, traditional elevation with modern performance.","img":"/products/classic/windows/ASG101 Hung Windows/Hung Windows.png"}},
  },
  "joinery": {
    "kitchens": {"name":"Kitchens","categoryLabel":"Custom Joinery","tagline":"Designed around how you cook, gather and live.","features":"Islands, integrated appliances, feature cabinetry","story":["Designed around how you cook, gather and live. Islands, integrated appliances, feature cabinetry.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/joinery-hero.png","storyImg":"/Atelier_Signature.png","description":"Designed around how you cook, gather and live. Islands, integrated appliances, feature cabinetry - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
    "butlers-pantries": {"name":"Butler's Pantries","categoryLabel":"Custom Joinery","tagline":"The hardworking second kitchen, concealed and organised.","features":"Appliance garages, tall storage, matched to the kitchen","story":["The hardworking second kitchen, concealed and organised. Appliance garages, tall storage, matched to the kitchen.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/Atelier_Signature.png","storyImg":"/Atelier_Classic.png","description":"The hardworking second kitchen, concealed and organised. Appliance garages, tall storage, matched to the kitchen - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
    "walk-in-wardrobes": {"name":"Walk-in Wardrobes","categoryLabel":"Custom Joinery","tagline":"Dressing spaces tailored around your wardrobe and daily routine.","features":"Integrated lighting, island drawers, custom storage","story":["Dressing spaces tailored around your wardrobe and daily routine. Integrated lighting, island drawers, custom storage.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/Atelier_Classic.png","storyImg":"/Atelier_Signature.png","description":"Dressing spaces tailored around your wardrobe and daily routine. Integrated lighting, island drawers, custom storage - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
    "bathroom-cabinetry": {"name":"Bathroom Cabinetry","categoryLabel":"Custom Joinery","tagline":"Refined cabinetry designed around the bathroom architecture.","features":"Floating vanities, shaving cabinets, integrated storage","story":["Refined cabinetry designed around the bathroom architecture. Floating vanities, shaving cabinets, integrated storage.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/vanities/OJS261-900A.jpg","storyImg":"/Atelier_Classic.png","description":"Refined cabinetry designed around the bathroom architecture. Floating vanities, shaving cabinets, integrated storage - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
    "laundries": {"name":"Laundries","categoryLabel":"Custom Joinery","tagline":"Practical, considered spaces designed to simplify the everyday.","features":"Concealed appliances, pull-out hampers, generous bench space","story":["Practical, considered spaces designed to simplify the everyday. Concealed appliances, pull-out hampers, generous bench space.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/Atelier_Classic.png","storyImg":"/Atelier_Classic.png","description":"Practical, considered spaces designed to simplify the everyday. Concealed appliances, pull-out hampers, generous bench space - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
    "entertainment-units": {"name":"Entertainment Units","categoryLabel":"Custom Joinery","tagline":"Media and display joinery that anchors the living space.","features":"Media cabinetry, display shelving, concealed cabling","story":["Media and display joinery that anchors the living space. Media cabinetry, display shelving, concealed cabling.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/Atelier_Signature.png","storyImg":"/Atelier_Classic.png","description":"Media and display joinery that anchors the living space. Media cabinetry, display shelving, concealed cabling - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
    "home-offices": {"name":"Home Offices","categoryLabel":"Custom Joinery","tagline":"Workspaces integrated into the architecture of the home.","features":"Built-in desks, library walls, concealed studies","story":["Workspaces integrated into the architecture of the home. Built-in desks, library walls, concealed studies.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/Atelier_Classic.png","storyImg":"/Atelier_Signature.png","description":"Workspaces integrated into the architecture of the home. Built-in desks, library walls, concealed studies - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
    "outdoor-kitchens": {"name":"Outdoor Kitchens","categoryLabel":"Custom Joinery","tagline":"Designed for entertaining beyond the interior.","features":"Aluminium cabinetry, BBQs, refrigeration and outdoor storage","story":["Designed for entertaining beyond the interior. Aluminium cabinetry, BBQs, refrigeration and outdoor storage.","Developed around your architectural plans, the material palette and how the space will be used - then documented in shop drawings and reviewed before manufacture."],"details":[{"label":"Includes","value":"Design, shop drawings & manufacture"},{"label":"Materials","value":"Premium, project-selected"},{"label":"Review","value":"Drawings reviewed before manufacture"},{"label":"Suitable For","value":"Residential"}],"sizes":["Custom to project plans"],"unit":"package","heroImg":"/Atelier_Signature.png","storyImg":"/Atelier_Classic.png","description":"Designed for entertaining beyond the interior. Aluminium cabinetry, BBQs, refrigeration and outdoor storage - made specifically for your project and documented in shop drawings before manufacture.","gallery":["/Atelier_Classic.png","/Atelier_Signature.png","/Atelier_Classic.png","/Atelier_Classic.png"]},
  },
  "bathrooms": {
    "the-mode": { name: "The Mode", packageStyle: "Modern Monochrome", categoryLabel: "Bathroom Packages", tagline: "Crisp black-and-white styling, matte-black fixtures, streamlined finishes and a strong contemporary architectural appearance.", story: ["Crisp black-and-white styling, matte-black fixtures, streamlined finishes and a strong contemporary architectural appearance.", "A fully coordinated bathroom package with every fixture, finish and surface selected to work together. Inspiration imagery is indicative only - final individual-product and complete-room photography will follow."], details: [{ label: "Style", value: "Modern Monochrome" }, { label: "Finish", value: "Matte Black" }, { label: "Palette", value: "Black & White" }, { label: "Suitable For", value: "Residential" }], sizes: ["Single vanity", "Double vanity"], unit: "package", heroImg: "/vanities/OJS273-800.jpg", storyImg: "/Atelier_Signature.png", gallery: ["/Atelier_Classic.png", "/Atelier_Signature.png", "/vanities/OJS272-400.jpg", "/vanities/OJS280-400.jpg"], fixedInclusions: [{ label: "Tapware finish", value: "Matte black" }, { label: "Tapware collection & design", value: "Squared, linear contemporary" }, { label: "Basin mixer", value: "Matte black square basin mixer" }, { label: "Shower mixer", value: "Matte black square shower mixer" }, { label: "Twin shower design", value: "Matte black square twin rail shower" }, { label: "LED mirror design", value: "Square-edge frameless LED mirror" }, { label: "Vanity profile, colour, finish & handles", value: "Flat handleless profile, matte white with matte black accent" }, { label: "Basin shape & material", value: "Rectangular semi-inset, matte white ceramic" }, { label: "Benchtop material & colour", value: "Ultra-white engineered stone, matte" }, { label: "Matching basin waste", value: "Matte black pop-up waste" }, { label: "Towel rail", value: "Matte black single rail" }, { label: "Toilet-roll holder", value: "Matte black holder" }, { label: "Package-specific tiles", value: "Crisp white large-format with black grout accents" }] },
    "the-estate": { name: "The Estate", packageStyle: "Contemporary Classic", categoryLabel: "Bathroom Packages", tagline: "Marble-inspired surfaces, sophisticated cabinetry, graceful detailing and polished finishes balanced with modern functionality.", story: ["Marble-inspired surfaces, sophisticated cabinetry, graceful detailing and polished finishes balanced with modern functionality.", "A fully coordinated bathroom package with every fixture, finish and surface selected to work together. Inspiration imagery is indicative only - final individual-product and complete-room photography will follow."], details: [{ label: "Style", value: "Contemporary Classic" }, { label: "Finish", value: "Brushed Nickel" }, { label: "Palette", value: "Marble & Stone-grey" }, { label: "Suitable For", value: "Residential" }], sizes: ["Single vanity", "Double vanity"], unit: "package", heroImg: "/Atelier_Signature.png", storyImg: "/Atelier_Classic.png", gallery: ["/Atelier_Signature.png", "/Atelier_Classic.png", "/vanities/OJS246-1200.jpg", "/vanities/OJS243-1200.jpg"], fixedInclusions: [{ label: "Tapware finish", value: "Brushed nickel" }, { label: "Tapware collection & design", value: "Softened classic lever" }, { label: "Basin mixer", value: "Brushed nickel basin mixer" }, { label: "Shower mixer", value: "Brushed nickel shower mixer" }, { label: "Twin shower design", value: "Brushed nickel twin rail shower" }, { label: "LED mirror design", value: "Soft-radius LED mirror with demister" }, { label: "Vanity profile, colour, finish & handles", value: "Shaker profile, satin stone-grey with fluted detail and brushed nickel handles" }, { label: "Basin shape & material", value: "Oval under-counter, gloss white ceramic" }, { label: "Benchtop material & colour", value: "Calacatta marble-look engineered stone, polished" }, { label: "Matching basin waste", value: "Brushed nickel pop-up waste" }, { label: "Towel rail", value: "Brushed nickel double rail" }, { label: "Toilet-roll holder", value: "Brushed nickel holder" }, { label: "Package-specific tiles", value: "Marble-look large-format with vertical feature" }] },
    "the-coast": { name: "The Coast", packageStyle: "Australian Coastal", categoryLabel: "Bathroom Packages", tagline: "Soft whites, pale timber tones and natural textures creating a light, relaxed and distinctly Australian character.", story: ["Soft whites, pale timber tones and natural textures creating a light, relaxed and distinctly Australian character.", "A fully coordinated bathroom package with every fixture, finish and surface selected to work together. Inspiration imagery is indicative only - final individual-product and complete-room photography will follow."], details: [{ label: "Style", value: "Australian Coastal" }, { label: "Finish", value: "Brushed Nickel" }, { label: "Palette", value: "Soft white & Pale timber" }, { label: "Suitable For", value: "Residential" }], sizes: ["Single vanity", "Double vanity"], unit: "package", heroImg: "/vanities/OJS265-1200.jpg", storyImg: "/Atelier_Classic.png", gallery: ["/vanities/OJS265-1200.jpg", "/Atelier_Classic.png", "/vanities/OJS277-900.jpg", "/vanities/OJS270-900.jpg"], fixedInclusions: [{ label: "Tapware finish", value: "Brushed nickel / chrome" }, { label: "Tapware collection & design", value: "Relaxed rounded" }, { label: "Basin mixer", value: "Brushed nickel rounded basin mixer" }, { label: "Shower mixer", value: "Brushed nickel rounded shower mixer" }, { label: "Twin shower design", value: "Brushed nickel round twin rail shower" }, { label: "LED mirror design", value: "Round LED mirror" }, { label: "Vanity profile, colour, finish & handles", value: "Shaker profile, pale oak timber-look with brushed nickel knobs" }, { label: "Basin shape & material", value: "Round above-counter, matte white ceramic" }, { label: "Benchtop material & colour", value: "Warm white engineered stone, honed" }, { label: "Matching basin waste", value: "Brushed nickel pop-up waste" }, { label: "Towel rail", value: "Brushed nickel single rail" }, { label: "Toilet-roll holder", value: "Brushed nickel holder" }, { label: "Package-specific tiles", value: "Soft white matte with natural-texture feature" }] },
    "the-terra": { name: "The Terra", packageStyle: "Organic Spa", categoryLabel: "Bathroom Packages", tagline: "Earthy stone, timber, sculptural forms and layered natural textures creating a calm, wellness-focused retreat.", story: ["Earthy stone, timber, sculptural forms and layered natural textures creating a calm, wellness-focused retreat.", "A fully coordinated bathroom package with every fixture, finish and surface selected to work together. Inspiration imagery is indicative only - final individual-product and complete-room photography will follow."], details: [{ label: "Style", value: "Organic Spa" }, { label: "Finish", value: "Brushed Brass" }, { label: "Palette", value: "Earthy stone & Timber" }, { label: "Suitable For", value: "Residential" }], sizes: ["Single vanity", "Double vanity"], unit: "package", heroImg: "/vanities/OJS270-900.jpg", storyImg: "/Atelier_Signature.png", gallery: ["/vanities/OJS270-900.jpg", "/Atelier_Signature.png", "/vanities/OJS266-800.jpg", "/vanities/OJS273-800.jpg"], fixedInclusions: [{ label: "Tapware finish", value: "Brushed brass" }, { label: "Tapware collection & design", value: "Sculptural organic" }, { label: "Basin mixer", value: "Brushed brass sculptural basin mixer" }, { label: "Shower mixer", value: "Brushed brass shower mixer" }, { label: "Twin shower design", value: "Brushed brass twin rail shower" }, { label: "LED mirror design", value: "Arch / pill LED mirror" }, { label: "Vanity profile, colour, finish & handles", value: "Curved profile, natural timber veneer, push-to-open (handleless)" }, { label: "Basin shape & material", value: "Oval above-counter, matte stone-look" }, { label: "Benchtop material & colour", value: "Travertine-look engineered stone, honed" }, { label: "Matching basin waste", value: "Brushed brass pop-up waste" }, { label: "Towel rail", value: "Brushed brass single rail" }, { label: "Toilet-roll holder", value: "Brushed brass holder" }, { label: "Package-specific tiles", value: "Earthy stone-look with terracotta feature" }] },
    "the-regent": { name: "The Regent", packageStyle: "Boutique Hotel Luxe", categoryLabel: "Bathroom Packages", tagline: "Rich timber, smoky stone, deep metallic finishes and warm ambient lighting for a dramatic premium atmosphere.", story: ["Rich timber, smoky stone, deep metallic finishes and warm ambient lighting for a dramatic premium atmosphere.", "A fully coordinated bathroom package with every fixture, finish and surface selected to work together. Inspiration imagery is indicative only - final individual-product and complete-room photography will follow."], details: [{ label: "Style", value: "Boutique Hotel Luxe" }, { label: "Finish", value: "Gunmetal" }, { label: "Palette", value: "Dark timber & Smoky stone" }, { label: "Suitable For", value: "Residential" }], sizes: ["Single vanity", "Double vanity"], unit: "package", heroImg: "/vanities/OJS246-1200.jpg", storyImg: "/Atelier_Classic.png", gallery: ["/vanities/OJS246-1200.jpg", "/Atelier_Classic.png", "/vanities/OJS276-1200.jpg", "/vanities/OJS274-800.jpg"], fixedInclusions: [{ label: "Tapware finish", value: "Gunmetal / dark bronze" }, { label: "Tapware collection & design", value: "Refined hotel-luxe" }, { label: "Basin mixer", value: "Gunmetal basin mixer" }, { label: "Shower mixer", value: "Gunmetal shower mixer" }, { label: "Twin shower design", value: "Gunmetal twin rail rain shower" }, { label: "LED mirror design", value: "Backlit feature LED mirror, warm light" }, { label: "Vanity profile, colour, finish & handles", value: "Fluted-front dark timber veneer with gunmetal handles" }, { label: "Basin shape & material", value: "Inset, matte smoky stone-look" }, { label: "Benchtop material & colour", value: "Smoky marble-look engineered stone, polished" }, { label: "Matching basin waste", value: "Gunmetal pop-up waste" }, { label: "Towel rail", value: "Gunmetal double rail" }, { label: "Toilet-roll holder", value: "Gunmetal holder" }, { label: "Package-specific tiles", value: "Smoky stone-look with metallic feature" }] },
  },
}

export function getProduct(category: string, product: string): ProductData | null {
  return ALL_PRODUCTS[category]?.[product] ?? null
}

export function listProducts(category: string): { slug: string; data: ProductData }[] {
  const c = ALL_PRODUCTS[category]
  if (!c) return []
  return Object.entries(c).map(([slug, data]) => ({ slug, data }))
}

/** Bathroom package-style products (those with a fixed `packageStyle`). */
export function listPackages(category: string): { slug: string; data: ProductData }[] {
  return listProducts(category).filter((p) => p.data.packageStyle)
}

/** Non-package component products (the "included products" library). */
export function listComponents(category: string): { slug: string; data: ProductData }[] {
  return listProducts(category).filter((p) => !p.data.packageStyle)
}

export const CLASSIC_CATEGORIES = Object.keys(CATEGORY_META)

// Windows & Doors product families - group the systems into platforms.
export type WdFamily = { slug: string; name: string; tagline: string; desc: string; slugs: string[] }
export const WD_FAMILIES: WdFamily[] = [
  { slug: "series-102", name: "Series 102", tagline: "Our most versatile Classic platform.", desc: "Built around a robust 102mm aluminium system, Series 102 brings sliding, awning, casement, pocket sliding and louvre configurations into one coordinated family. Designed for larger openings, generous glazing and contemporary Australian homes, it gives projects the flexibility to maintain a consistent architectural language across multiple window and door types.", slugs: ["asg-series-102", "asg-102-awning", "asg-102-casement", "asg-102-pocket", "asg-102-louvre"] },
  { slug: "series-86", name: "Series 86", tagline: "Streamlined performance for everyday spaces.", desc: "Series 86 is a clean, space-efficient aluminium platform designed for practical residential applications. Available in sliding and awning configurations, its slimmer 86mm system provides dependable everyday performance while maximising natural light and preserving valuable internal and external space.", slugs: ["asg-series-86", "asg-86-awning"] },
  { slug: "series-75", name: "Series 75", tagline: "Designed to open the home completely.", desc: "Series 75 is our dedicated folding door platform, created for projects seeking a broad, uninterrupted connection between indoor and outdoor living. Multiple glazed panels fold and stack neatly to the side, allowing living, dining and alfresco spaces to operate as one connected environment.", slugs: ["asg-series-75"] },
  { slug: "series-101", name: "Series 101", tagline: "Classic proportions with practical vertical ventilation.", desc: "Series 101 brings the timeless character of a hung window into a contemporary aluminium system. Available in single- or double-hung configurations, its vertical sliding operation provides natural ventilation without projecting into internal rooms, walkways or landscaped areas.", slugs: ["asg-series-101"] },
]
export function getFamily(slug: string): WdFamily | null {
  return WD_FAMILIES.find((f) => f.slug === slug) ?? null
}
