// Custom Joinery FAQs, shared by the page and its FAQPage structured data.
export const JOINERY_FAQS = [
  { q: "Can I choose my own colours, finishes and hardware?", a: "Yes. Every joinery package is detailed to your selections - colours, door profiles, benchtop material, handles or handleless and internal hardware. If you already know what you want, send us your finishes schedule. If you're still deciding, send inspiration images or photographs of joinery you like and we'll translate them into a specification and proposal." },
  { q: "Can you accommodate integrated appliances?", a: "Yes. Provide the appliance make and model numbers (or the installation manuals) and we'll detail the cabinetry to suit - integrated fridges and dishwashers, under-bench ovens, rangehoods, microwaves and wine fridges. Appliances themselves are supplied by you or your builder unless otherwise stated." },
  { q: "Do you provide installation?", a: "Yes. Installation is available through our licensed installation partners, or we can supply joinery as a supply-only package where installation is managed by your builder or nominated trades. Either way, the joinery arrives on site as a documented, labelled package with the drawings your installer needs." },
  { q: "How do you account for site tolerances?", a: "We build installation tolerance into the detailing stage. Where appropriate we incorporate filler panels, scribes and adjustment allowances so cabinetry can be fitted cleanly to walls, floors and ceilings that are never perfectly plumb or square. Where a fixed dimension is critical (for example an integrated appliance opening or a stone benchtop), we confirm it before manufacture." },
  { q: "Can I make changes after receiving the proposal?", a: "Yes. Dimensions in the initial proposal are indicative and based on your plans, so the pricing is a reliable guide rather than a final measure. Measuring and confirming every joinery piece to the millimetre is a detailed exercise, so we do it with you once you decide to proceed - that's when we resolve the finer details, finalise the drawings and confirm the final price before manufacture begins." },
  { q: "Can you work directly with my architect, interior designer or builder?", a: "Yes. We work from architectural drawings, interior design documentation and finishes schedules, and coordinate with your builder on programme, delivery and installation." },
  { q: "Do you supply stone benchtops?", a: "Yes - natural stone and quartz surfaces coordinated with the joinery so cut-outs, overhangs and support are detailed together." },
  { q: "What is the lead time?", a: "Typically 8-12 weeks from confirmed drawings and deposit to delivery, depending on scope, finishes and season. We confirm the programme in your proposal and coordinate the delivery date with your builder." },
  { q: "Do you offer a warranty?", a: "Yes. Our joinery is manufactured to Australian cabinetry standards and covered by a written warranty on workmanship and hardware." },
  { q: "Can you supply joinery for an entire home?", a: "Yes. We can coordinate multiple joinery areas as one package - from kitchens and butler's pantries through to wardrobes, laundries, bathrooms, media joinery, home offices, built-in storage and outdoor kitchens. This allows finishes, hardware and detailing to remain consistent throughout the project." },
];
